//! `CompletionCandidate` — raw completion item produced by providers.

use std::cmp::Ordering;
use std::fmt;

/// The kind/category of a completion candidate — used for icon display and grouping.
///
/// Each variant maps to a specific source of completion candidates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum CompletionKind {
    /// A registered command name from the Command Registry.
    Command,
    /// A file path from VFS.
    FilePath,
    /// A directory entry (shown with trailing separator).
    Directory,
    /// A command keyword or modifier (e.g., CHARS, PREFIX, VISIBLE).
    Keyword,
    /// A registered Lua macro name.
    Macro,
    /// A line command kind (e.g., CC, DD, M5).
    LineCommand,
    /// A plugin-provided custom candidate.
    Plugin,
}

impl fmt::Display for CompletionKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Command => write!(f, "Command"),
            Self::FilePath => write!(f, "File"),
            Self::Directory => write!(f, "Directory"),
            Self::Keyword => write!(f, "Keyword"),
            Self::Macro => write!(f, "Macro"),
            Self::LineCommand => write!(f, "LineCommand"),
            Self::Plugin => write!(f, "Plugin"),
        }
    }
}

/// A raw completion candidate produced by a `CompletionProvider`.
///
/// Contains all information needed for filtering, ranking, and display.
/// Candidates are generated by providers and later filtered/ranked by
/// the matching and ranking layers before being presented to the user.
#[derive(Debug, Clone)]
pub struct CompletionCandidate {
    /// The display label shown in the popup.
    pub label: String,
    /// The text to insert when this candidate is accepted.
    pub insert_text: String,
    /// The category or source of this candidate (for grouping/icons).
    pub kind: CompletionKind,
    /// Optional detail text shown alongside the label (e.g., command category).
    pub detail: Option<String>,
    /// Optional longer description for tooltip display.
    pub description: Option<String>,
    /// Provider-assigned relevance weight (higher = more relevant). Default 0.
    pub base_relevance: i32,
}

impl CompletionCandidate {
    /// Creates a new candidate with required fields and default relevance.
    pub fn new(
        label: impl Into<String>,
        insert_text: impl Into<String>,
        kind: CompletionKind,
    ) -> Self {
        Self {
            label: label.into(),
            insert_text: insert_text.into(),
            kind,
            detail: None,
            description: None,
            base_relevance: 0,
        }
    }

    /// Sets the detail text and returns self for builder chaining.
    pub fn with_detail(mut self, detail: impl Into<String>) -> Self {
        self.detail = Some(detail.into());
        self
    }

    /// Sets the description and returns self for builder chaining.
    pub fn with_description(mut self, desc: impl Into<String>) -> Self {
        self.description = Some(desc.into());
        self
    }

    /// Sets the base relevance weight and returns self for builder chaining.
    pub fn with_relevance(mut self, relevance: i32) -> Self {
        self.base_relevance = relevance;
        self
    }
}

impl fmt::Display for CompletionCandidate {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} ({})", self.label, self.kind)
    }
}

impl PartialEq for CompletionCandidate {
    fn eq(&self, other: &Self) -> bool {
        self.label == other.label
            && self.insert_text == other.insert_text
            && self.kind == other.kind
    }
}

impl Eq for CompletionCandidate {}

impl PartialOrd for CompletionCandidate {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for CompletionCandidate {
    /// Orders candidates by base_relevance (descending), then by label length
    /// (ascending, shorter first), then alphabetically by label.
    fn cmp(&self, other: &Self) -> Ordering {
        other
            .base_relevance
            .cmp(&self.base_relevance)
            .then_with(|| self.label.len().cmp(&other.label.len()))
            .then_with(|| self.label.cmp(&other.label))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Validates: Requirement 2 (candidate construction)
    #[test]
    fn candidate_construction_sets_fields() {
        let c = CompletionCandidate::new("FIND", "find", CompletionKind::Command)
            .with_detail("search")
            .with_description("Find text in document")
            .with_relevance(10);

        assert_eq!(c.label, "FIND");
        assert_eq!(c.insert_text, "find");
        assert_eq!(c.kind, CompletionKind::Command);
        assert_eq!(c.detail.as_deref(), Some("search"));
        assert_eq!(c.description.as_deref(), Some("Find text in document"));
        assert_eq!(c.base_relevance, 10);
    }

    // Validates: Requirement 2.4 (ordering by sort_priority then label)
    #[test]
    fn candidates_ordered_by_relevance_then_length_then_name() {
        let a =
            CompletionCandidate::new("FIND", "find", CompletionKind::Command).with_relevance(10);
        let b =
            CompletionCandidate::new("FILTER", "filter", CompletionKind::Command).with_relevance(5);
        let c =
            CompletionCandidate::new("FILE", "file", CompletionKind::Command).with_relevance(10);

        // a (relevance 10) should come before b (relevance 5)
        assert!(a < b);
        // a (FIND, len 4) and c (FILE, len 4) have same relevance and length
        // so they compare alphabetically: FILE < FIND
        assert!(c < a);
    }

    // Validates: Requirement 2.2 (kind discrimination)
    #[test]
    fn kind_display_differentiates_types() {
        assert_eq!(CompletionKind::Command.to_string(), "Command");
        assert_eq!(CompletionKind::FilePath.to_string(), "File");
        assert_eq!(CompletionKind::Directory.to_string(), "Directory");
        assert_eq!(CompletionKind::Keyword.to_string(), "Keyword");
        assert_eq!(CompletionKind::Macro.to_string(), "Macro");
        assert_eq!(CompletionKind::LineCommand.to_string(), "LineCommand");
        assert_eq!(CompletionKind::Plugin.to_string(), "Plugin");
    }

    // Validates: Requirement 2.3 (Display, Debug, Clone, PartialEq, Eq)
    #[test]
    fn candidate_display_shows_label_and_kind() {
        let c = CompletionCandidate::new("SAVE", "save", CompletionKind::Command);
        assert_eq!(c.to_string(), "SAVE (Command)");
    }

    #[test]
    fn candidate_equality_checks_label_insert_text_and_kind() {
        let a = CompletionCandidate::new("FIND", "find", CompletionKind::Command);
        let b =
            CompletionCandidate::new("FIND", "find", CompletionKind::Command).with_relevance(99); // relevance doesn't affect equality
        let c = CompletionCandidate::new("FIND", "find", CompletionKind::Keyword);

        assert_eq!(a, b);
        assert_ne!(a, c); // different kind
    }

    #[test]
    fn candidate_clone_produces_equal_value() {
        let c = CompletionCandidate::new("TEST", "test", CompletionKind::Macro)
            .with_detail("detail")
            .with_description("desc")
            .with_relevance(5);
        let cloned = c.clone();
        assert_eq!(c, cloned);
        assert_eq!(c.detail, cloned.detail);
        assert_eq!(c.description, cloned.description);
        assert_eq!(c.base_relevance, cloned.base_relevance);
    }
}
