//! Automatic bug report generation for FFTest assertion failures.
//!
//! Appends structured entries to `reports/bugs-from-tests.md` whenever an
//! assertion fails. The format is compatible with `docs/status/bugs.md`.
//!
//! Validates: Requirement 12.1, 12.2, 12.3, 12.4, 12.5 (automated-dialog-testing)

use std::fs;
use std::io::{self, Write};
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::time::{SystemTime, UNIX_EPOCH};

// === Sequential bug ID counter =============================================

static NEXT_BUG_ID: AtomicUsize = AtomicUsize::new(1);

/// Reset the in-process bug ID counter (for test isolation only).
#[doc(hidden)]
pub fn reset_bug_id_counter() {
    NEXT_BUG_ID.store(1, Ordering::SeqCst);
}

// === BugEntry ==============================================================

/// A single structured bug entry produced from a failed assertion.
///
/// Validates: Requirement 12.2
#[derive(Debug, Clone)]
pub struct BugEntry {
    /// Sequential identifier in the form `BT-NNN`.
    pub id: String,
    /// Path to the script file that produced the failure.
    pub script_file: String,
    /// 1-based line number of the failing assertion.
    pub line: usize,
    /// The assertion text as it appeared in the script.
    pub assertion_text: String,
    /// The expected value, if applicable.
    pub expected: Option<String>,
    /// The actual value observed, if applicable.
    pub actual: Option<String>,
    /// UTC timestamp of the failure (seconds since Unix epoch as a string).
    pub timestamp: String,
}

impl BugEntry {
    /// Create a new `BugEntry` with an auto-incremented ID and current timestamp.
    pub fn new(
        script_file: impl Into<String>,
        line: usize,
        assertion_text: impl Into<String>,
        expected: Option<String>,
        actual: Option<String>,
    ) -> Self {
        let id_num = NEXT_BUG_ID.fetch_add(1, Ordering::SeqCst);
        let id = format!("BT-{id_num:03}");
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map(|d| d.as_secs().to_string())
            .unwrap_or_else(|_| "0".to_string());
        Self {
            id,
            script_file: script_file.into(),
            line,
            assertion_text: assertion_text.into(),
            expected,
            actual,
            timestamp,
        }
    }

    /// Format this entry as a Markdown table row compatible with `docs/status/bugs.md`.
    ///
    /// Validates: Requirement 12.3
    pub fn to_table_row(&self) -> String {
        let expected = self.expected.as_deref().unwrap_or("--");
        let actual = self.actual.as_deref().unwrap_or("--");
        format!(
            "| {} | OPEN | Medium | `ff-fftest` | {} (line {}) | -- | {} | expected: {} actual: {} |",
            self.id,
            self.assertion_text,
            self.line,
            self.timestamp,
            expected,
            actual,
        )
    }
}

// === BugReporter ===========================================================

/// Appends bug entries to `reports/bugs-from-tests.md`.
///
/// Validates: Requirement 12.1, 12.4, 12.5
pub struct BugReporter {
    report_path: std::path::PathBuf,
}

impl BugReporter {
    /// Create a reporter that writes to `<reports_dir>/bugs-from-tests.md`.
    pub fn new(reports_dir: impl AsRef<Path>) -> Self {
        Self {
            report_path: reports_dir.as_ref().join("bugs-from-tests.md"),
        }
    }

    /// Append a bug entry to the report file.
    ///
    /// Creates the file with a header row if it does not exist (Req 12.4).
    /// Does nothing if called with no failures (callers must check before calling).
    ///
    /// # Errors
    ///
    /// Returns `io::Error` if the file cannot be created or written.
    ///
    /// Validates: Requirement 12.1, 12.4
    pub fn append(&self, entry: &BugEntry) -> io::Result<()> {
        let needs_header = !self.report_path.exists();

        // Ensure parent directory exists.
        if let Some(parent) = self.report_path.parent() {
            fs::create_dir_all(parent)?;
        }

        let mut file = fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.report_path)?;

        if needs_header {
            writeln!(
                file,
                "# FFTest Bug Report\n\
                 \n\
                 Auto-generated by the FFTest runner. Copy rows into `docs/status/bugs.md`.\n\
                 \n\
                 | ID | Status | Severity | Component | Description | Req | Timestamp | Notes |\n\
                 |----|--------|----------|-----------|-------------|-----|-----------|-------|"
            )?;
        }

        writeln!(file, "{}", entry.to_table_row())?;
        Ok(())
    }
}

// === Tests =================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    // Validates: Requirement 12.2 -- BugEntry fields populated correctly
    #[test]
    fn bug_entry_fields_populated_correctly() {
        reset_bug_id_counter();
        let entry = BugEntry::new(
            "tests/dialog/pom.fftest",
            5,
            "ASSERT CONTEXT IS \"Home\"",
            Some("Home".to_string()),
            Some("Editor".to_string()),
        );
        assert!(entry.id.starts_with("BT-"));
        assert_eq!(entry.script_file, "tests/dialog/pom.fftest");
        assert_eq!(entry.line, 5);
        assert_eq!(entry.assertion_text, "ASSERT CONTEXT IS \"Home\"");
        assert_eq!(entry.expected.as_deref(), Some("Home"));
        assert_eq!(entry.actual.as_deref(), Some("Editor"));
        assert!(!entry.timestamp.is_empty());
    }

    // Validates: Requirement 12.3 -- table row format compatible with bugs.md
    #[test]
    fn table_row_contains_required_fields() {
        reset_bug_id_counter();
        let entry = BugEntry::new(
            "tests/dialog/pom.fftest",
            5,
            "ASSERT CONTEXT IS \"Home\"",
            Some("Home".to_string()),
            Some("Editor".to_string()),
        );
        let row = entry.to_table_row();
        assert!(row.starts_with("| BT-"));
        assert!(row.contains("OPEN"));
        assert!(row.contains("ff-fftest"));
        assert!(row.contains("line 5"));
        assert!(row.contains("Home"));
        assert!(row.contains("Editor"));
    }

    // Validates: Requirement 12.4 -- file created with header when absent
    #[test]
    fn creates_file_with_header_when_absent() {
        reset_bug_id_counter();
        let dir = TempDir::new().expect("tempdir");
        let reporter = BugReporter::new(dir.path());
        let entry = BugEntry::new("test.fftest", 1, "ASSERT FILE OPEN", None, None);
        reporter.append(&entry).expect("append ok");
        let content = fs::read_to_string(dir.path().join("bugs-from-tests.md")).expect("read ok");
        assert!(content.contains("# FFTest Bug Report"));
        assert!(content.contains("| ID |"));
        assert!(content.contains("BT-"));
    }

    // Validates: Requirement 12.4 -- header not duplicated on second append
    #[test]
    fn header_not_duplicated_on_second_append() {
        reset_bug_id_counter();
        let dir = TempDir::new().expect("tempdir");
        let reporter = BugReporter::new(dir.path());
        let e1 = BugEntry::new("test.fftest", 1, "ASSERT FILE OPEN", None, None);
        let e2 = BugEntry::new("test.fftest", 2, "ASSERT FILE OPEN", None, None);
        reporter.append(&e1).expect("first append ok");
        reporter.append(&e2).expect("second append ok");
        let content = fs::read_to_string(dir.path().join("bugs-from-tests.md")).expect("read ok");
        assert_eq!(content.matches("# FFTest Bug Report").count(), 1);
    }

    // Validates: Requirement 12.5 -- no file created when no failures
    #[test]
    fn no_file_created_when_no_failures() {
        let dir = TempDir::new().expect("tempdir");
        let report_path = dir.path().join("bugs-from-tests.md");
        // Do not call append -- simulates all-pass run
        assert!(!report_path.exists());
    }

    // Validates: Requirement 12.2 -- sequential IDs increment
    #[test]
    fn sequential_ids_increment() {
        reset_bug_id_counter();
        let e1 = BugEntry::new("a.fftest", 1, "ASSERT FILE OPEN", None, None);
        let e2 = BugEntry::new("b.fftest", 2, "ASSERT FILE OPEN", None, None);
        assert_ne!(e1.id, e2.id);
        // Both should be BT-NNN format
        assert!(e1.id.starts_with("BT-"));
        assert!(e2.id.starts_with("BT-"));
    }
}
