path = r"C:\workspace\VSC\FileForgeWorkbench\crates\ff-desktop\src\session_manager.rs"
with open(path, "rb") as f:
    data = f.read()

print(f"File size: {len(data)} bytes")

# Patch FileEditor arm in save() to include workspace_name
old_fe_save = (
    b"                TabKind::FileEditor => t.path.as_ref().map(|path| SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FileEditor,\n"
    b"                    uri: Some(path.clone()),\n"
    b"                    viewport_top_line: t.viewport.top_line() as usize,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: t.cursor.cursor_line() as usize,\n"
    b"                    caret_column: t.cursor.cursor_column() as usize,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                }),\n"
    b"                TabKind::FilesPanel => Some(SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FilesPanel,\n"
    b"                    uri: None,\n"
    b"                    viewport_top_line: 1,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: 1,\n"
    b"                    caret_column: 1,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                }),\n"
    b"                TabKind::FileExplorerPanel => Some(SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FileExplorerPanel,\n"
    b"                    uri: None,\n"
    b"                    viewport_top_line: 1,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: 1,\n"
    b"                    caret_column: 1,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                }),\n"
    b"                TabKind::PrimaryOptionMenu\n"
    b"                | TabKind::Untitled\n"
    b"                | TabKind::SettingsPanel\n"
    b"                | TabKind::SearchResults\n"
    b"                | TabKind::PluginManager\n"
    b"                | TabKind::EventLog\n"
    b"                | TabKind::MacroLibrary => None,\n"
    b"            })\n"
    b"            .collect();\n"
    b"\n"
    b"        let active_tab_id = {\n"
    b"            let active = tabs.active_tab();\n"
    b"            match active.kind {\n"
    b"                TabKind::FileEditor => active.path.as_ref().map(|_| format!(\"{}\", active.id.0)),\n"
    b"                TabKind::FilesPanel => Some(format!(\"{}\", active.id.0)),\n"
    b"                TabKind::PrimaryOptionMenu\n"
    b"                | TabKind::Untitled\n"
    b"                | TabKind::SettingsPanel\n"
    b"                | TabKind::FileExplorerPanel\n"
    b"                | TabKind::SearchResults\n"
    b"                | TabKind::PluginManager\n"
    b"                | TabKind::EventLog\n"
    b"                | TabKind::MacroLibrary => None,\n"
    b"            }\n"
    b"        };\n"
    b"        // Note: FileExplorerPanel active_tab_id is None (no URI to track)\n"
    b"\n"
    b"        let state = SessionState {\n"
    b"            tabs: session_tabs,\n"
    b"            active_tab_id,\n"
    b"            global_zoom_offset: zoom_offset,\n"
    b"            key_bar_visible,\n"
    b"            file_explorer_sidebar_width,\n"
    b"            ..SessionState::empty()\n"
    b"        };\n"
    b"\n"
    b"        // Best-effort \xe2\x80\x94 ignore write errors (graceful degradation)\n"
    b"        let _ = self.session_file.save(&state);\n"
    b"    }\n"
    b"\n"
    b"    /// Like `save`, but also persists the active workspace path."
)

new_fe_save = (
    b"                TabKind::FileEditor => t.path.as_ref().map(|path| SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FileEditor,\n"
    b"                    uri: Some(path.clone()),\n"
    b"                    viewport_top_line: t.viewport.top_line() as usize,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: t.cursor.cursor_line() as usize,\n"
    b"                    caret_column: t.cursor.cursor_column() as usize,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                    workspace_name: t.workspace_name.clone(),\n"
    b"                }),\n"
    b"                TabKind::FilesPanel => Some(SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FilesPanel,\n"
    b"                    uri: None,\n"
    b"                    viewport_top_line: 1,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: 1,\n"
    b"                    caret_column: 1,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                    workspace_name: t.workspace_name.clone(),\n"
    b"                }),\n"
    b"                TabKind::FileExplorerPanel => Some(SessionTabState {\n"
    b"                    tab_id: format!(\"{}\", t.id.0),\n"
    b"                    tab_kind: PersistedTabKind::FileExplorerPanel,\n"
    b"                    uri: None,\n"
    b"                    viewport_top_line: 1,\n"
    b"                    viewport_horizontal_offset: 0,\n"
    b"                    caret_line: 1,\n"
    b"                    caret_column: 1,\n"
    b"                    selections: Vec::new(),\n"
    b"                    language_override: None,\n"
    b"                    is_pinned: false,\n"
    b"                    zoom_offset: 0,\n"
    b"                    workspace_name: t.workspace_name.clone(),\n"
    b"                }),\n"
    b"                TabKind::PrimaryOptionMenu\n"
    b"                | TabKind::Untitled\n"
    b"                | TabKind::SettingsPanel\n"
    b"                | TabKind::SearchResults\n"
    b"                | TabKind::PluginManager\n"
    b"                | TabKind::EventLog\n"
    b"                | TabKind::MacroLibrary => None,\n"
    b"            })\n"
    b"            .collect();\n"
    b"\n"
    b"        let active_tab_id = {\n"
    b"            let active = tabs.active_tab();\n"
    b"            match active.kind {\n"
    b"                TabKind::FileEditor => active.path.as_ref().map(|_| format!(\"{}\", active.id.0)),\n"
    b"                TabKind::FilesPanel => Some(format!(\"{}\", active.id.0)),\n"
    b"                TabKind::PrimaryOptionMenu\n"
    b"                | TabKind::Untitled\n"
    b"                | TabKind::SettingsPanel\n"
    b"                | TabKind::FileExplorerPanel\n"
    b"                | TabKind::SearchResults\n"
    b"                | TabKind::PluginManager\n"
    b"                | TabKind::EventLog\n"
    b"                | TabKind::MacroLibrary => None,\n"
    b"            }\n"
    b"        };\n"
    b"        // Note: FileExplorerPanel active_tab_id is None (no URI to track)\n"
    b"\n"
    b"        let state = SessionState {\n"
    b"            tabs: session_tabs,\n"
    b"            active_tab_id,\n"
    b"            global_zoom_offset: zoom_offset,\n"
    b"            key_bar_visible,\n"
    b"            file_explorer_sidebar_width,\n"
    b"            ..SessionState::empty()\n"
    b"        };\n"
    b"\n"
    b"        // Best-effort \xe2\x80\x94 ignore write errors (graceful degradation)\n"
    b"        let _ = self.session_file.save(&state);\n"
    b"    }\n"
    b"\n"
    b"    /// Like `save`, but also persists the active workspace path."
)

if old_fe_save in data:
    data = data.replace(old_fe_save, new_fe_save, 1)
    print("save() patched with workspace_name")
else:
    print("ERROR: save() pattern not found")

with open(path, "wb") as f:
    f.write(data)

print("Done")
